### ISSUE TITLE
[Feature Request] Fortune Avenue should display the file name of the frb file you have opened

### ISSUE THREAD

**Issue by MysticMismagius** [FortuneStreetModding/fortune-avenue-qt#19]

**Comment by Sophilautia** [comment]
This should be re-opened, I find 2.6.1 does not display the filename of the board I've opened.
![FortuneAvenue_2022-11-17_22-28-55](https://user-images.githubusercontent.com/10488699/202434820-ce44e96b-fdde-4676-ae01-ef1cd583344b.png)

**Comment by Sophilautia** [comment]
@Deflaktor @Landmaster
