### ISSUE TITLE
Parity with Yaml Editing

### ISSUE THREAD

**Issue by Sophilautia** [FortuneStreetModding/fortune-avenue-qt#24]
Right now, Fortune Avenue has fields for Starting Amount, Goal Amount etc. But this information is also spelled out in the yaml. It's confusing which of the two CSMM actually pulls the data from. Perhaps these variables should be removed from one or the other to make things clearer.

**Comment by MysticMismagius** [comment]
In these instances the answer is actually both.
The game uses the main.dol to determine starting cash in single player only, and default target net worth in all modes.
The game uses the .frb file to determine starting cash in multiplayer, and max dice roll in all modes.

**Comment by Sophilautia** [comment]
Huh, so it actually IS necessary.. It would be nice if this was made less redundant, but I guess that's probably a lot of work and low priority right now.

**Comment by Deflaktor** [comment]
Fixed with eed4251d412aa363bb2e653adf3dfbaf8a634d73
The other redundant things still need to be removed in csmm and the yaml file
