### ISSUE TITLE
Support for unused shop models

### ISSUE THREAD

**Issue by MysticMismagius** [FortuneStreetModding/fortune-avenue-qt#3]
There are 30 shop names (or shop models in fortune avenue) that go unused but are perfectly functional. 
There is support for them in old .NET versions of the editor, but not in Qt versions.

Landmaster said they were planning to add support for them in the future, so I'm putting this issue here so it isn't forgotten

**Comment by Landmaster** [comment]
https://github.com/FortuneStreetModding/fortune-avenue-qt/commit/e6449706b15b70f7bfa4acfe74baa8d5e3bf213b

**Comment by Landmaster** [comment]
Actually there's some stuff that I still need to add for this to be fully functional, hold up
