### ISSUE TITLE
[Feature Request] Edit square number

### ISSUE THREAD

**Issue by Sophilautia** [FortuneStreetModding/fortune-avenue-qt#35]
A function to manually edit a square's ID number would be helpful for a few reasons. For one, if you're trying to use one way exits to create an unelectable square, the ID number is important. And also, when the game has to edit multiple shop prices at once, it will go in order of square ID.

Perhaps set it so if you change to an already existing ID number then it pushes that and all successive IDs up one.

**Comment by Landmaster** [comment]
2.6.0
